from Lista_1 import Vector 
v1=Vector(3)
v2=Vector(5)
v3=Vector()
print("\nwektory v1, v2, v3: ", v1, v2, v3, "\n")
Vector.generator(v1)
Vector.chage_list(v3, [1,2,3])
print("losowo wygenerowane wartości v1 i ustawione wybrane wartości v3:", v1, v3, "\n\n")
print("dodanie i odejmowanie v1 i v3\n",  v1+v3, v1-v3, "\n")
print("v1*(-2), v2*1.5, v3*3", v1*(-2), v2*1.5, v3*3, "\n")
print("długości v1 i v3: ", Vector.długość(v1), (Vector.długość(v3)), "\n")
print("suma elementów v3 i v2: ", Vector.suma_elementów(v3), " | ", Vector.suma_elementów(v2), "\n")
print("ilczyn skalarny v1 i v3", Vector.ilczyn_skalarny(v1,v3), "\n")
print("1(2 nie pythonowo)element v1 i v2", v1[1], " | ", v2[1], "\n")
print("czy 3, 4 należą do v3?", 3 in v3, " | ", 4 in v3)